service: pizzawizard

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  # role: ** Set Role Here

functions:
  pizzaMe:
    handler: handler.findPizza
    events:
      - http:
          method: post
          path: pizza